# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField(default='', max_length=1000)),
                ('wikipedia', models.URLField(blank=True)),
                ('tripadvisor', models.URLField(blank=True)),
                ('google_map', models.URLField(blank=True)),
                ('web_site', models.URLField(blank=True)),
                ('town', models.CharField(blank=True, default='', max_length=30)),
                ('image', models.ImageField(blank=True, default='no_image.png', upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('text', models.TextField(default='', max_length=1000)),
                ('wikipedia', models.URLField(blank=True)),
                ('tripadvisor', models.URLField(blank=True)),
                ('google_map', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, default='no_image.png', upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
