# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='image_map',
            field=models.ImageField(blank=True, default='no_image.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='towns',
            name='image_map',
            field=models.ImageField(blank=True, default='no_image.png', upload_to=''),
        ),
    ]
