# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 08:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_auto_20170918_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=25)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+x xxx xxx xx xx'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('order', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
    ]
